// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blufnflduulthulxlsvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsdWZuZmxkdXVsdGh1bHhsc3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTgxMDksImV4cCI6MjA2NDYzNDEwOX0.g2aPRU9z1uwLS4Z4ENxlbIrcLxIaYOjoVoG2Ce9Zn4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);